### ISSUE TITLE
Remove vendor folders & documentation

### ISSUE THREAD

**Issue by florello-tbox** [WangMichael/threapy-box#1]
Remove `node_modules` and `vendor` from repository.
Please add a few lines of documentation about how to re-install them.
Include all the steps required to install correctly this web site as well.

Bonus points if you move config's credentials on environment variables, but not required.

**Comment by WangMichael** [comment]
Hello, I can remove node_modules but cannot remove vendor folder. node_modules are Node files which we can safely remove. But vendor is a composer folder which I need to load the PSR-4 dependency for this project.

**Comment by florello-tbox** [comment]
Hi Wang,
requesting a `composer install` after `git clone` is a perfect dev experience for us, we don't want keep the `vendor` folder with the deps or composer's autoloader there - we want to re-install them each time we deploy.

Thanks.
