### ISSUE TITLE
Bug fix - login issue

### ISSUE THREAD

**Issue by florello-tbox** [WangMichael/threapy-box#5]
Starting with clean cookies, after registration, this is what I get after log in, _on the **dev** env_:

![alt text](https://image.ibb.co/mfg3tn/Screenshot_from_2018_05_08_16_58_29.png)

If I refresh the same page, I'll be correctly redirected to `/dashboard/` -- please fix that Notice, and explain the cause of the problem ( i.e, why the user wasn't redirected anyway the first time? )

Thanks.

**Comment by WangMichael** [comment]
<img width="1639" alt="screen shot 2018-05-08 at 17 14 00" src="https://user-images.githubusercontent.com/14076239/39769179-6377751c-52e3-11e8-9afe-92c1d80d9a70.png">

**Comment by WangMichael** [comment]
As for the login, It is meant to be like this. After the user logged in, they should be directed into the dashboard page rather than login page

**Comment by WangMichael** [comment]
If you want to log out, Please try the url '/log_out/'

**Comment by WangMichael** [comment]
It will destroy the user session and quit

**Comment by florello-tbox** [comment]
My version is `PHP 7.1.15`. To replicate the issue, please raise the `error_reporting` to `-1`, and keep enabled `display_errors`.

```
Notice: A session had already been started - ignoring session_start()
```

**Comment by WangMichael** [comment]
The session is a way to keep track of the user information in the server. It plays an important to perform different tasks such as authentication, authorisation and payment stage tracking. I will fix it immediately. If you want to debug it, you can just add another condition to test if the session has already started. After the modification, the syntax should:

if(!session_id())
    session_start()

hope that helps

**Comment by florello-tbox** [comment]
Perfect, thanks.
Do you know what was the problem with/what caused the other two Warnings on the screenshot?

**Comment by WangMichael** [comment]
Hello,

For HTTP, a response will follow after the header information has been sent. If the response has been sent, there is no way to change the header information except through output_start(). But I am a bit confused here that I did not send out any output before line 107. How come it produced an error like this? Besides, there is not any error or warning produced on my side even though I raise the error reporting to be -1 from E_ALL. I do not really where the problem comes from, to be honest?

**Comment by florello-tbox** [comment]
>  How come it produced an error like this?

The last warning ( Cannot modify header information ) is a direct consequence of the other first two error, since errors in thise case were written to `stdout`. By fixing the first one you also fix the second, and by doing that also the third one in one go.

Perfect, we can close this issue :+1:
